name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    permissions:
      contents: read
    strategy:
      matrix:
        os:
          - macos-15
          - ubuntu-latest
        bazel:
          - version: latest
            extra_info_flags: ""
          - version: last_rc
            extra_info_flags: ""
          - version: last_green
            # https://github.com/bazelbuild/bazel/issues/25145
            extra_info_flags: "--noincompatible_target_cpu_from_platform"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: test (${{ matrix.os }}, ${{ matrix.bazel.version }})
    env:
      USE_BAZEL_VERSION: ${{ matrix.bazel.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Bazel Info
        run: |
          bazel version
          bazel info ${{ matrix.bazel.extra_info_flags }}
      - run: bazel test //...
